dist: xenial
language: python
python: "3.7"
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
services:
  - postgresql
before_install:
  - pip install pipenv pytest coveralls
before_script:
  - psql -c 'CREATE DATABASE testdb;' -U postgres
install:
  - pipenv install --dev
script:
  - pipenv run pytest -vv --color=yes --cov=dh_backend --cov-report term-missing:skip-covered ./tests
after_success:
  - coveralls