"""empty message

Revision ID: 0eb81a09c7d1
Revises: c3c671e14422
Create Date: 2019-05-13 14:34:46.275008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb81a09c7d1'
down_revision = 'c3c671e14422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deck', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Deck', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Deck', type_='foreignkey')
    op.drop_column('Deck', 'user_id')
    # ### end Alembic commands ###
