"""empty message

Revision ID: 21b627083eb7
Revises: d9c20aa3f76b
Create Date: 2019-05-18 12:37:14.235703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b627083eb7'
down_revision = 'd9c20aa3f76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TwitchSession',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TwitchSession')
    # ### end Alembic commands ###
