"""empty message

Revision ID: 2479caccac75
Revises: c15c79af89c3
Create Date: 2019-05-08 07:53:49.868927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2479caccac75'
down_revision = 'c15c79af89c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deck', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Deck', 'DeckVersion', ['current_version_id'], ['id'], ondelete='SET NULL')
    op.add_column('DeckVersion', sa.Column('deck_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'DeckVersion', ['id'])
    op.create_foreign_key(None, 'DeckVersion', 'Deck', ['deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'DeckVersion', type_='foreignkey')
    op.drop_constraint(None, 'DeckVersion', type_='unique')
    op.drop_column('DeckVersion', 'deck_id')
    op.drop_constraint(None, 'Deck', type_='foreignkey')
    op.drop_column('Deck', 'current_version_id')
    # ### end Alembic commands ###
