"""empty message

Revision ID: 2810cb2fe13c
Revises: a27c12adf22b
Create Date: 2019-05-08 07:44:45.707150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2810cb2fe13c'
down_revision = 'a27c12adf22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Deck',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Deck')
    # ### end Alembic commands ###
