"""empty message

Revision ID: 4679a3f06ee9
Revises: d3a65e13f1ed
Create Date: 2019-05-19 14:11:34.797375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4679a3f06ee9'
down_revision = 'd3a65e13f1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TwitchSession', sa.Column('twitch_session_token', sa.String(), nullable=True))
    op.drop_column('User', 'twitch_auth_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('twitch_auth_session', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('TwitchSession', 'twitch_session_token')
    # ### end Alembic commands ###
