"""empty message

Revision ID: 8410f339dbac
Revises: a0a1db663fb5
Create Date: 2019-06-05 12:39:30.479125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8410f339dbac'
down_revision = 'a0a1db663fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('deck_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game', 'DeckVersion', ['deck_version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'deck_version_id')
    # ### end Alembic commands ###
