"""empty message

Revision ID: 9be8f083788b
Revises: e4809888fc4c
Create Date: 2019-06-06 15:00:07.053306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be8f083788b'
down_revision = 'e4809888fc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DeckVersion', sa.Column('last_played', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DeckVersion', 'last_played')
    # ### end Alembic commands ###
