"""empty message

Revision ID: a0a1db663fb5
Revises: 4679a3f06ee9
Create Date: 2019-06-05 12:36:22.621701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a1db663fb5'
down_revision = '4679a3f06ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opponent_name', sa.String(), nullable=True),
    sa.Column('opponent_deck', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('result', sa.Enum('RESULT_UNKNOWN', 'RESULT_LOSS', 'RESULT_WIN', 'RESULT_DRAW', name='gameresult'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
