"""empty message

Revision ID: be50aa2fd4f4
Revises: 21b627083eb7
Create Date: 2019-05-18 14:23:38.914413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be50aa2fd4f4'
down_revision = '21b627083eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TwitchSession', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'TwitchSession', 'User', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TwitchSession', type_='foreignkey')
    op.drop_column('TwitchSession', 'user_id')
    # ### end Alembic commands ###
