"""empty message

Revision ID: c15c79af89c3
Revises: 2810cb2fe13c
Create Date: 2019-05-08 07:48:10.034203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15c79af89c3'
down_revision = '2810cb2fe13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DeckVersion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deck_name', sa.String(length=32), nullable=False),
    sa.Column('deck_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'Deck', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Deck', type_='unique')
    op.drop_table('DeckVersion')
    # ### end Alembic commands ###
