"""empty message

Revision ID: c3c671e14422
Revises: e251c1343426
Create Date: 2019-05-13 12:12:42.055739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c671e14422'
down_revision = 'e251c1343426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('RecentDeck', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('RecentDeck_user_id_fkey', 'RecentDeck', type_='foreignkey')
    op.create_foreign_key(None, 'RecentDeck', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('User', sa.Column('api_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'api_key')
    op.drop_constraint(None, 'RecentDeck', type_='foreignkey')
    op.create_foreign_key('RecentDeck_user_id_fkey', 'RecentDeck', 'User', ['user_id'], ['id'])
    op.alter_column('RecentDeck', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
