"""empty message

Revision ID: ca12296ca8b5
Revises: cac79134df9b
Create Date: 2019-05-19 13:51:05.945359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca12296ca8b5'
down_revision = 'cac79134df9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TwitchAccount', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TwitchAccount', sa.Column('email', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
