"""empty message

Revision ID: cac79134df9b
Revises: 29d0dfb933ae
Create Date: 2019-05-19 13:37:48.768342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac79134df9b'
down_revision = '29d0dfb933ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TwitchAccount', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'TwitchAccount', 'User', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TwitchAccount', type_='foreignkey')
    op.drop_column('TwitchAccount', 'user_id')
    # ### end Alembic commands ###
