"""empty message

Revision ID: d3a65e13f1ed
Revises: ca12296ca8b5
Create Date: 2019-05-19 13:51:28.599357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a65e13f1ed'
down_revision = 'ca12296ca8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TwitchAccount', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TwitchAccount', 'email')
    # ### end Alembic commands ###
