"""empty message

Revision ID: d9c20aa3f76b
Revises: 0eb81a09c7d1
Create Date: 2019-05-17 21:01:04.075047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c20aa3f76b'
down_revision = '0eb81a09c7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Deck_user_id_fkey', 'Deck', type_='foreignkey')
    op.create_foreign_key(None, 'Deck', 'User', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('User', sa.Column('twitch_auth_session', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'twitch_auth_session')
    op.drop_constraint(None, 'Deck', type_='foreignkey')
    op.create_foreign_key('Deck_user_id_fkey', 'Deck', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###
