"""empty message

Revision ID: e4809888fc4c
Revises: 8410f339dbac
Create Date: 2019-06-06 14:39:28.559047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4809888fc4c'
down_revision = '8410f339dbac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deck', sa.Column('loss_count', sa.Integer(), nullable=True))
    op.add_column('Deck', sa.Column('win_count', sa.Integer(), nullable=True))
    op.add_column('DeckVersion', sa.Column('loss_count', sa.Integer(), nullable=True))
    op.add_column('DeckVersion', sa.Column('win_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DeckVersion', 'win_count')
    op.drop_column('DeckVersion', 'loss_count')
    op.drop_column('Deck', 'win_count')
    op.drop_column('Deck', 'loss_count')
    # ### end Alembic commands ###
